client
dev {{ .Device }}
proto {{ .Proto }}
remote {{ .ServerAddress }} {{ .OpenVpnServerPort }} {{ .Proto }}
{{ .ResolveRetry }}
nobind
user {{ .OVClientUser }}
group {{ .OVClientGroup }}
{{ .PersistTun }}
{{ .PersistKey }}
{{ .RemoteCertTLS }}
cipher {{ .Cipher }}
auth {{ .Auth }}
{{ .AuthNoCache }}
{{ .TlsClient }}
verb {{ .Verbose }}
{{ .AuthUserPass }}
{{ .CustomConfOne }}
{{ .CustomConfTwo }}
{{ .CustomConfThree }}
<ca>
{{ .Ca }}
</ca>
<cert>
{{ .Cert }}
</cert>
<key>
{{ .Key }}
</key>
<tls-crypt>
{{ .Ta }}
</tls-crypt>
# Auto generated by OpenVPN-UI v.0.9.5.6